name: Shuttle deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Check source
        run: |
          cargo check
      - name: Install shuttle cli
        run: |
          cargo install cargo-quickinstall
          cargo quickinstall cargo-shuttle
      - name: Log into shuttle
        run: |
          cargo shuttle login --api-key ${{ secrets.SHUTTLE_DEPLOY_KEY }}
      - name: Deploy to shuttle
        run:
          cargo shuttle deploy | awk '!/Database URI.*?$/'