name: Shuttle deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check source
        run: |
          cargo check
      - uses: kaleidawave/shuttle-deploy-action@add-action
        with:
          shuttle-deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
