name: Shuttle deploy

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          shuttle-deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
